INSERT INTO books(author, title, size) VALUES ('Dostoevsky', 'Idiot', 350)
INSERT INTO books(author, title, size) VALUES ('Pushkin', 'Onegin', 153)
INSERT INTO books(author, title, size) VALUES ('Vasiliev', 'Belaya Kniga', 400)
INSERT INTO books(author, title, size) VALUES ('Pushkin', 'Dubrovsky', 100)
INSERT INTO books(author, title, size) VALUES ('Pushkin', 'Captain''s Daughter', 119)
INSERT INTO books(author, title, size) VALUES ('Ibuka', 'Kindergarten is too late', 252)
INSERT INTO books(author, title, size) VALUES ('Rand', 'Introduction', 670)
INSERT INTO books(author, title, size) VALUES ('Rand-McNally', 'Official Railway Guide', 150)
INSERT INTO books(author, title, size) VALUES ('God', 'Bible', 701)
